mkdir -p output/randvsezr/greater_than_or_equals_6
rm -f output/randvsezr/greater_than_or_equals_6/*
python3 hw3.py -t data/greater_than_or_equals_6/sol-6d-c2-obj1.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/sol-6d-c2-obj1.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-T.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-T.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-S.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-S.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-P.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-P.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-V.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-V.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-U.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-U.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-J.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-J.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/pom3c.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/pom3c.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/auto93.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/auto93.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/coc1000.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/coc1000.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-H.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-H.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-I.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-I.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/X264_AllMeasurements.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/X264_AllMeasurements.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/xomo_ground.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/xomo_ground.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-Q.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-Q.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/xomo_osp2.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/xomo_osp2.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-N.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-N.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-O.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-O.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/pom3d.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/pom3d.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/rs-6d-c3_obj2.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/rs-6d-c3_obj2.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-K.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-K.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/xomo_osp.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/xomo_osp.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/Apache_AllMeasurements.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/Apache_AllMeasurements.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-R.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-R.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/pom3a.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/pom3a.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-M.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-M.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/pom3b.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/pom3b.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/nasa93dem.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/nasa93dem.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-W.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-W.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-X.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-X.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/healthCloseIsses12mths0011-easy.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/healthCloseIsses12mths0011-easy.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/HSMGP_num.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/HSMGP_num.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/healthCloseIsses12mths0001-hard.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/healthCloseIsses12mths0001-hard.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SS-L.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SS-L.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/xomo_flight.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/xomo_flight.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/SQL_AllMeasurements.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/SQL_AllMeasurements.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/Wine_quality.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/Wine_quality.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/wc-6d-c1-obj1.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/wc-6d-c1-obj1.csv & 
python3 hw3.py -t data/greater_than_or_equals_6/rs-6d-c3_obj1.csv -e randvsezr  | tee output/randvsezr/greater_than_or_equals_6/rs-6d-c3_obj1.csv & 
